# -*- coding: utf-8 -*-
from typing import List

import disnake

color_dict = {
    "Default": disnake.Colour.default(),
    "Blue": disnake.Colour.blue(),
    "Blurple": disnake.Colour.blurple(),
    "Brand_green": disnake.Colour.brand_green(),
    "Brand_red": disnake.Colour.brand_red(),
    "Dark_blue": disnake.Colour.dark_blue(),
    "Dark_gold": disnake.Colour.dark_gold(),
    "Dark_green": disnake.Colour.dark_green(),
    "Dark_magenta": disnake.Colour.dark_magenta(),
    "Dark_orange": disnake.Colour.dark_orange(),
    "Dark_purple": disnake.Colour.dark_purple(),
    "Dark_red": disnake.Colour.dark_red(),
    "Dark_teal": disnake.Colour.dark_teal(),
    "Dark_theme": disnake.Colour.dark_theme(),
    "Fuchsia": disnake.Colour.fuchsia(),
    "Gold": disnake.Colour.gold(),
    "Green": disnake.Colour.green(),
    "Lighter_gray": disnake.Colour.lighter_gray(),
    "Magenta": disnake.Colour.magenta(),
    "Og_blurple": disnake.Colour.og_blurple(),
    "Orange": disnake.Colour.orange(),
    "Purple": disnake.Colour.purple(),
    "Red": disnake.Colour.red(),
    "Teal": disnake.Colour.teal(),
    "Yellow": disnake.Colour.yellow(),
}

alphabet: List[str] = [
    "🇦",
    "🇧",
    "🇨",
    "🇩",
    "🇪",
    "🇫",
    "🇬",
    "🇭",
    "🇮",
    "🇯",
    "🇰",
    "🇱",
    "🇲",
    "🇳",
    "🇴",
    "🇵",
    "🇶",
    "🇷",
    "🇸",
    "🇹",
    "🇺",
    "🇻",
    "🇼",
    "🇽",
    "🇾",
    "🇿",
]
